# Generated by Django 3.1.4 on 2020-12-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(blank=True, through='routes.RouteStop', to='routes.Stop'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='next_stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_stop', to='routes.routestop'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
