# Generated by Django 3.1.4 on 2020-12-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20201207_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
