# Generated by Django 3.1.4 on 2020-12-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20201207_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='custom_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
