# Generated by Django 3.1.4 on 2020-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20201214_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
